"""add_task_count_to_task_lists

Revision ID: 2d2b719bf968
Revises: 4610b5efb515
Create Date: 2026-06-10 15:49:00.939034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d2b719bf968'
down_revision: Union[str, Sequence[str], None] = '4610b5efb515'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_lists', sa.Column('task_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###
    op.execute(
        "UPDATE task_lists SET task_count = ("
        "  SELECT COUNT(*) FROM tasks WHERE tasks.task_list_id = task_lists.id"
        ")"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_lists', 'task_count')
    # ### end Alembic commands ###
