"""add_indexes_for_performance

Revision ID: 4610b5efb515
Revises: 4fea5ca91439
Create Date: 2026-06-10 15:33:38.817000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4610b5efb515'
down_revision: Union[str, Sequence[str], None] = '4fea5ca91439'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_task_lists_owner_id', 'task_lists', ['owner_id'], unique=False)
    op.create_index('ix_tasks_task_list_id_status_priority', 'tasks', ['task_list_id', 'status', 'priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_task_list_id_status_priority', table_name='tasks')
    op.drop_index('ix_task_lists_owner_id', table_name='task_lists')
    # ### end Alembic commands ###
